image: qdrant/qdrant:latest
container_name: qdrant
ports:
  - "${PORT_6333}:6333" # HTTP API 端口
  - "${PORT_6334}:6334" # gRPC 端口
volumes:
  # 数据持久化目录
  - "${MOUNT_DIR}/storage:/qdrant/storage"
  # 配置文件
  - "${MOUNT_DIR}/config:/qdrant/config"
environment:
  - TZ=Asia/Shanghai
    # API Key 用于认证请求
  - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    # 日志级别
  - QDRANT__LOG_LEVEL=INFO
    # 将 payload 存盘以节省内存
  - QDRANT__STORAGE__ON_DISK_PAYLOAD=true
